<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:11.
 */
class QueryAggregateOperationTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var QueryAggregateOperation
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new QueryAggregateOperation();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Box\QueryAggregateOperation::andSub
	 */
	public function testAndSub() {
		$sub = QuerySubCondition::create()->endsWith('lol', 'face');

		$token = $this->object->andSub($sub);

		$this->assertTrue($token instanceof TokenOperationAndSub);
	}

	/**
	 * @covers Box\QueryAggregateOperation::orSub
	 */
	public function testOrSub() {
		$sub   = QuerySubCondition::create();
		$token = $this->object->orSub($sub);

		$this->assertTrue($token instanceof TokenOperationOrSub);
	}

	/**
	 * @covers Box\QueryAggregateOperation::and_
	 */
	public function testAnd_() {
		$token = $this->object->and_();

		$this->assertTrue($token instanceof TokenOperationAnd);
	}

	/**
	 * @covers Box\QueryAggregateOperation::or_
	 */
	public function testOr_() {
		$token = $this->object->or_();

		$this->assertTrue($token instanceof TokenOperationOr);
	}
}
