<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:08.
 */
class QueryOperationTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var QueryOperation
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new QueryOperation;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Box\QueryOperation::andSub
	 */
	public function testAndSub() {
		$sub = QuerySubCondition::create();

		$instance = $this->object->andSub($sub);

		$this->assertTrue($instance instanceof QueryOperation);
	}

	/**
	 * @covers Box\QueryOperation::orSub
	 */
	public function testOrSub() {
		$sub = QuerySubCondition::create();

		$instance = $this->object->orSub($sub);

		$this->assertTrue($instance instanceof QueryOperation);
	}

	/**
	 * @covers Box\QueryOperation::and_
	 */
	public function testAnd_() {
		$instance = $this->object->and_();

		$this->assertTrue($instance instanceof QueryCondition);
	}

	/**
	 * @covers Box\QueryOperation::or_
	 */
	public function testOr_() {
		$instance = $this->object->or_();

		$this->assertTrue($instance instanceof QueryCondition);
	}
}
