<?php

namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:07.
 */
class QueryConditionTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var QueryCondition
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new QueryCondition;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Box\QueryCondition::contains
	 * @todo   Implement testContains().
	 */
	public function testContains() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::endsWith
	 * @todo   Implement testEndsWith().
	 */
	public function testEndsWith() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::startsWith
	 * @todo   Implement testStartsWith().
	 */
	public function testStartsWith() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::equals
	 * @todo   Implement testEquals().
	 */
	public function testEquals() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::notEquals
	 * @todo   Implement testNotEquals().
	 */
	public function testNotEquals() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::greaterThan
	 * @todo   Implement testGreaterThan().
	 */
	public function testGreaterThan() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::greaterThanOrEquals
	 * @todo   Implement testGreaterThanOrEquals().
	 */
	public function testGreaterThanOrEquals() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::lessThan
	 * @todo   Implement testLessThan().
	 */
	public function testLessThan() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::lessThanOrEquals
	 * @todo   Implement testLessThanOrEquals().
	 */
	public function testLessThanOrEquals() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::in
	 * @todo   Implement testIn().
	 */
	public function testIn() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QueryCondition::notIn
	 * @todo   Implement testNotIn().
	 */
	public function testNotIn() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
