<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:08.
 */
class QuerySubConditionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var QuerySubCondition
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = QuerySubCondition::create();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Box\QuerySubCondition::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::getToken
     * @todo   Implement testGetToken().
     */
    public function testGetToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::contains
     * @todo   Implement testContains().
     */
    public function testContains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::endsWith
     * @todo   Implement testEndsWith().
     */
    public function testEndsWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::startsWith
     * @todo   Implement testStartsWith().
     */
    public function testStartsWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::equals
     * @todo   Implement testEquals().
     */
    public function testEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::notEquals
     * @todo   Implement testNotEquals().
     */
    public function testNotEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::greaterThan
     * @todo   Implement testGreaterThan().
     */
    public function testGreaterThan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::greaterThanOrEquals
     * @todo   Implement testGreaterThanOrEquals().
     */
    public function testGreaterThanOrEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::lessThan
     * @todo   Implement testLessThan().
     */
    public function testLessThan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::lessThanOrEquals
     * @todo   Implement testLessThanOrEquals().
     */
    public function testLessThanOrEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::in
     * @todo   Implement testIn().
     */
    public function testIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QuerySubCondition::notIn
     * @todo   Implement testNotIn().
     */
    public function testNotIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
