<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:07.
 */
class QueryOffsetTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var QueryOffset
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new QueryOffset;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Box\QueryOffset::offset
	 */
	public function testOffset() {
		$this->assertNull($this->object->offset(42));
	}
}
