<?php

namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-19 at 15:37:20.
 */
class QuerySubOperationTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var QuerySubOperation
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new QuerySubOperation;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Box\QuerySubOperation::andSub
	 */
	public function testAndSub() {
		$this->assertTrue($this->object->andSub(QuerySubCondition::create()->equals('property', 42)) instanceof QuerySubOperation);
	}

	/**
	 * @covers Box\QuerySubOperation::orSub
	 */
	public function testOrSub() {
		$this->assertTrue($this->object->orSub(QuerySubCondition::create()->equals('property', 42)) instanceof QuerySubOperation);
	}

	/**
	 * @covers Box\QuerySubOperation::and_
	 */
	public function testAnd_() {
		$this->assertTrue($this->object->and_() instanceof QuerySubCondition);
	}

	/**
	 * @covers Box\QuerySubOperation::or_
	 */
	public function testOr_() {
		$this->assertTrue($this->object->or_() instanceof QuerySubCondition);
	}

}
