<?php

namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-19 at 15:37:20.
 */
class QuerySubOperationTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var QuerySubOperation
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new QuerySubOperation;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Box\QuerySubOperation::andSub
	 * @todo   Implement testAndSub().
	 */
	public function testAndSub() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QuerySubOperation::orSub
	 * @todo   Implement testOrSub().
	 */
	public function testOrSub() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QuerySubOperation::and_
	 * @todo   Implement testAnd_().
	 */
	public function testAnd_() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Box\QuerySubOperation::or_
	 * @todo   Implement testOr_().
	 */
	public function testOr_() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
