<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:07.
 */
class QueryLimitOrOrderByTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var QueryLimitOrOrderBy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QueryLimitOrOrderBy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Box\QueryLimitOrOrderBy::limit
     * @todo   Implement testLimit().
     */
    public function testLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\QueryLimitOrOrderBy::orderBy
     * @todo   Implement testOrderBy().
     */
    public function testOrderBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
