<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:07.
 */
class QueryLimitOrOrderByTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var QueryLimitOrOrderBy
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new QueryLimitOrOrderBy;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Box\QueryLimitOrOrderBy::limit
	 */
	public function testLimit() {
		$instance = $this->object->limit(42);

		$this->assertTrue($instance instanceof QueryOffset);
	}

	/**
	 * @covers Box\QueryLimitOrOrderBy::orderBy
	 */
	public function testOrderBy() {
		$instance = $this->object->orderBy('property', QueryLimitOrOrderBy::ASC);
		$this->assertTrue($instance instanceof QueryLimitOrOrderBy);

		$instance = $this->object->orderBy('property2', QueryLimitOrOrderBy::DESC);
		$this->assertTrue($instance instanceof QueryLimitOrOrderBy);
	}
}
