<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:13.
 */
class TokenNativePseudoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TokenNativePseudo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TokenNativePseudo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Box\TokenNativePseudo::contains
     * @todo   Implement testContains().
     */
    public function testContains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::endsWidth
     * @todo   Implement testEndsWidth().
     */
    public function testEndsWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::equals
     * @todo   Implement testEquals().
     */
    public function testEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::greaterThan
     * @todo   Implement testGreaterThan().
     */
    public function testGreaterThan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::greaterThanOrEquals
     * @todo   Implement testGreaterThanOrEquals().
     */
    public function testGreaterThanOrEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::in
     * @todo   Implement testIn().
     */
    public function testIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::lessThan
     * @todo   Implement testLessThan().
     */
    public function testLessThan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::lessThanOrEquals
     * @todo   Implement testLessThanOrEquals().
     */
    public function testLessThanOrEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::notEquals
     * @todo   Implement testNotEquals().
     */
    public function testNotEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::notIn
     * @todo   Implement testNotIn().
     */
    public function testNotIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::startsWith
     * @todo   Implement testStartsWith().
     */
    public function testStartsWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::andOperator
     * @todo   Implement testAndOperator().
     */
    public function testAndOperator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::andSubOperator
     * @todo   Implement testAndSubOperator().
     */
    public function testAndSubOperator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::orOperator
     * @todo   Implement testOrOperator().
     */
    public function testOrOperator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::orSubOperator
     * @todo   Implement testOrSubOperator().
     */
    public function testOrSubOperator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::limit
     * @todo   Implement testLimit().
     */
    public function testLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::offset
     * @todo   Implement testOffset().
     */
    public function testOffset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::orderBy
     * @todo   Implement testOrderBy().
     */
    public function testOrderBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Box\TokenNativePseudo::root
     * @todo   Implement testRoot().
     */
    public function testRoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
