<?php
namespace Box;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-08 at 15:09:13.
 */
class TokenNativePseudoTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var TokenNativePseudo
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new TokenNativePseudo;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Box\TokenNativePseudo::contains
	 */
	public function testContains() {
		$this->assertInternalType('string', $this->object->equals(new TokenConditionEquals(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::endsWidth
	 */
	public function testEndsWidth() {
		$this->assertInternalType('string', $this->object->endsWidth(new TokenConditionEndsWith(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::equals
	 */
	public function testEquals() {
		$this->assertInternalType('string', $this->object->equals(new TokenConditionEquals(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::greaterThan
	 */
	public function testGreaterThan() {
		$this->assertInternalType('string', $this->object->greaterThan(new TokenConditionGreaterThan(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::greaterThanOrEquals
	 */
	public function testGreaterThanOrEquals() {
		$this->assertInternalType('string', $this->object->greaterThanOrEquals(new TokenConditionGreaterThanOrEquals(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::in
	 */
	public function testIn() {
		$this->assertInternalType('string', $this->object->in(new TokenConditionIn(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::lessThan
	 */
	public function testLessThan() {
		$this->assertInternalType('string', $this->object->lessThan(new TokenConditionLessThan(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::lessThanOrEquals
	 */
	public function testLessThanOrEquals() {
		$this->assertInternalType('string', $this->object->lessThanOrEquals(new TokenConditionLessThanOrEquals(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::notEquals
	 */
	public function testNotEquals() {
		$this->assertInternalType('string', $this->object->notEquals(new TokenConditionNotEquals(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::notIn
	 */
	public function testNotIn() {
		$this->assertInternalType('string', $this->object->notIn(new TokenConditionNotIn(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::startsWith
	 */
	public function testStartsWith() {
		$this->assertInternalType('string', $this->object->startsWith(new TokenConditionStartsWith(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::andOperator
	 */
	public function testAndOperator() {
		$this->assertInternalType('string', $this->object->andOperator(new TokenOperationAnd(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::andSubOperator
	 */
	public function testAndSubOperator() {
		$this->assertInternalType('string', $this->object->andSubOperator(new TokenOperationAndSub(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::orOperator
	 */
	public function testOrOperator() {
		$this->assertInternalType('string', $this->object->orOperator(new TokenOperationOr(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::orSubOperator
	 */
	public function testOrSubOperator() {
		$this->assertInternalType('string', $this->object->orSubOperator(new TokenOperationOrSub(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::limit
	 */
	public function testLimit() {
		$this->assertInternalType('string', $this->object->limit(new TokenLimit(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::offset
	 */
	public function testOffset() {
		$this->assertInternalType('string', $this->object->offset(new TokenOffset(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::orderBy
	 */
	public function testOrderBy() {
		$this->assertInternalType('string', $this->object->orderBy(new TokenOrderBy(), null));
	}

	/**
	 * @covers Box\TokenNativePseudo::root
	 */
	public function testRoot() {
		$this->assertInternalType('string', $this->object->root(new TokenRoot(), null));
	}
}
